// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartJuniorTestTask.Db;

#nullable disable

namespace SmartJuniorTestTask.Migrations
{
    [DbContext(typeof(MsSqlDbContext))]
    partial class MsSqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartJuniorTestTask.Models.EquipmentPlacementContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumberOfEquipmentUnits")
                        .HasColumnType("int");

                    b.Property<int>("ProductionFacilityCode")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfProcessEquipmentCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductionFacilityCode");

                    b.HasIndex("TypeOfProcessEquipmentCode");

                    b.ToTable("EquipmentPlacementContracts");
                });

            modelBuilder.Entity("SmartJuniorTestTask.Models.ProductionFacility", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StandardAreaForEquipment")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("ProductionFacilities");
                });

            modelBuilder.Entity("SmartJuniorTestTask.Models.TypeOfProcessEquipment", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("TypeOfProcessEquipment");
                });

            modelBuilder.Entity("SmartJuniorTestTask.Models.EquipmentPlacementContract", b =>
                {
                    b.HasOne("SmartJuniorTestTask.Models.ProductionFacility", "ProductionFacility")
                        .WithMany()
                        .HasForeignKey("ProductionFacilityCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartJuniorTestTask.Models.TypeOfProcessEquipment", "TypeOfProcessEquipment")
                        .WithMany()
                        .HasForeignKey("TypeOfProcessEquipmentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionFacility");

                    b.Navigation("TypeOfProcessEquipment");
                });
#pragma warning restore 612, 618
        }
    }
}
