version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y" 
      SA_PASSWORD: "YourStrong!Password123" 
    volumes:
      - mssql_data:/var/opt/mssql 

volumes:
  mssql_data:
    driver: local